# Packages installed to the root file system

IMAGE_INSTALL += "modem-shutdown"
#IMAGE_INSTALL += "msmirqbalance"
IMAGE_INSTALL += "start-scripts-misc-daemon"
IMAGE_INSTALL += "start-scripts-qseecomd-daemon"
IMAGE_INSTALL += "start-scripts-sfs-config"
IMAGE_INSTALL += "start-scripts-le-updater"
IMAGE_INSTALL += "ss-services"
IMAGE_INSTALL += "q6-admin-adsp"
IMAGE_INSTALL += "adsprpc"
#IMAGE_INSTALL += "sensors"

#IMAGE_INSTALL_ATTEMPTONLY += "fastmmi"
IMAGE_INSTALL += "lib32-fastmmi"

IMAGE_INSTALL += "q6-admin-slpi"

IMAGE_INSTALL += "sensors-see-commonsys-intf"
IMAGE_INSTALL += "sensors-see"
IMAGE_INSTALL += "lib32-sensors-see-commonsys-intf"
IMAGE_INSTALL += "lib32-sensors-see"
