#!/bin/sh

# ---------------------------------------------------------------------------
# Copyright (c) 2018 Qualcomm Technologies, Inc.
# All Rights Reserved.
# Confidential and Proprietary - Qualcomm Technologies, Inc.
# ---------------------------------------------------------------------------

slot=$(abctl --boot_slot)

if test "$slot" == "_a" -o "$slot" == "_b" ; then
   abctl --set_success
   sync
fi
